import { NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'

export async function POST(req: Request) {
    try {
        const supabase = createClient()
        const { data: { user } } = await supabase.auth.getUser()

        if (!user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const body = await req.json()

        // Call AI API (Groq Example)
        const apiKey = process.env.AI_API_KEY
        let aiFormattedContent = null

        if (!apiKey) {
            console.warn("No AI_API_KEY provided. Skipping AI generation and saving raw data.")
            aiFormattedContent = JSON.stringify({
                summary: body.personalInfo.summary || "Summary generated by AI would appear here.",
                experience: body.experience,
                education: body.education,
                skills: body.skills.split(',').map((s: string) => s.trim())
            })
        } else {
            const prompt = `
Rewrite the following resume content to be:
- Professional
- ATS-friendly
- Use strong action verbs
- Quantify achievements
- Improve grammar and clarity

Return ONLY a structured JSON with this exact format, no markdown formatting or other text:
{
  "summary": "...",
  "experience": [{"company": "...", "position": "...", "startDate": "...", "endDate": "...", "description": "..."}],
  "education": [{"institution": "...", "degree": "...", "field": "...", "startDate": "...", "endDate": "..."}],
  "skills": ["...", "..."]
}

User Data:
${JSON.stringify(body)}
`

            const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${apiKey}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    model: 'llama3-8b-8192',
                    messages: [{ role: 'user', content: prompt }],
                    temperature: 0.5,
                    response_format: { type: "json_object" }
                })
            })

            if (!response.ok) {
                throw new Error('Failed to generate AI content')
            }

            const result = await response.json()
            aiFormattedContent = result.choices[0].message.content
        }

        // Save to Supabase
        const { data: insertedResume, error: dbError } = await supabase
            .from('resumes')
            .insert({
                user_id: user.id,
                title: `${body.personalInfo.fullName}'s Resume`,
                personal_info: body.personalInfo,
                experience: body.experience,
                education: body.education,
                skills: body.skills.split(',').map((s: string) => s.trim()),
                ai_generated_content: aiFormattedContent
            })
            .select()
            .single()

        if (dbError) throw dbError

        return NextResponse.json({ success: true, resumeId: insertedResume.id })
    } catch (error: any) {
        console.error(error)
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 })
    }
}
